apiVersion: v1
kind: Service
metadata:
  name: {{ packageJson.name }}-udp
spec:
  type: LoadBalancer
  loadBalancerIP: {{ loadBalancerIp }}
  selector:
    app: {{ packageJson.name }}
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: {{ packageJson.name }}-tcp
spec:
  type: LoadBalancer
  loadBalancerIP: {{ loadBalancerIp }}
  selector:
    app: {{ packageJson.name }}
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53