apiVersion: v1
kind: Service
metadata:
  name: {{ packageJson.name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ loadBalancerIp }}
  selector:
    app: {{ packageJson.name }}
  ports:
  - protocol: UDP
    port: 5333
    targetPort: 5333
  # - protocol: TCP
    # port: 5333
    # targetPort: 5333