apiVersion: v1
kind: Service
metadata:
  name: {{ packageJson.name }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ loadBalancerIp }}
  selector:
    app: {{ packageJson.name }}
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53